config2:
  globalConfig:
    runIDExtension: testExport
    transformerName: facebook/esm2_t6_8M_UR50D
    gpu_vina: true
    vina_gpu_cuda_path: /home/cewinharhar/GITHUB/Vina-GPU-2.0/Vina-GPU+
    vina_path: /home/cewinharhar/GITHUB/vina_1.2.3_linux_x86_64
    autoDockScript_path: /home/cewinharhar/GITHUB/AutoDock-Vina/example/autodock_scripts
    metal_containing: true
    ligandNr: 8                 #which ligand to use 
  
  gaespConfig:
    wildTypeAASeq: MSTETLRLQKARATEEGLAFETPGGLTRALRDGCFLLAVPPGFDTTPGVTLCREFFRPVEQGGESTRAYRGFRDLDGVYFDREHFQTEHVLIDGPGRERHFPPELRRMAEHMHELARHVLRTVLTELGVARELWSEVTGGAVDGRGTEWFAANHYRSERDRLGCAPHKDTGFVTVLYIEEGGLEAATGGSWTPVDPVPGCFVVNFGGAFELLTSGLDRPVRALLHRVRQCAPRPESADRFSFAAFVNPPPTGDLYRVGADGTATVARSTEDFLRDFNERTWGDGYADFGIAPPEPAGVAEDGVRA
    wildTypeStructurePath: /home/cewinharhar/GITHUB/reincatalyze/data/raw/aKGD_FE_oxo_relaxed.pdb
    thread: 8000
    num_modes: 5
    boxSize: 15
    gaespSeed: 42
    exhaustiveness: 16 
    dockingTool: vinagpu   

  pyroprolexConfig:
    mutationApproach: pyrosetta
  
  residoraConfig:
    max_ep_len: 1               #max timesteps in one episode
    max_training_timesteps: 1  # break training loop if timeteps > max_training_timesteps
    save_model_freq: 25         # save model frequency (in num timesteps)
    K_epochs: 50                # update policy for K epochs
    eps_clip: 0.5               # clip parameter for PPO
    gamma: 0.99                 # discount factor
    lr_actor: 0.0009            # learning rate for actor network
    lr_critic: 0.003            # learning rate for critic network
    residoraSeed: 13             # set random seed if required (0 : no random seed)

    nrNeuronsInHiddenLayers: 
      - 256                     #list format
    activationFunction : tanh
    useCNN          : False
    stride          : 4         #only if useCNN true
    kernel_size     : 6         #IF YOU CHANGE ABOVE 6 YOU LOOSE 2 DIMs
    out_channel     : 2         #only if useCNN true
    dropOutProb     : 0.01
    residoraDevice  : cpu
